In [1]:
import pandas as pd

# Working with json

In [2]:
pd.read_json('iris.json')

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

# Working with sql

In [4]:
pip install mysql.connector

Requirement already satisfied: mysql.connector in d:\anaconda\lib\site-packages (2.2.9)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import mysql.connector

In [7]:
conn=mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [10]:
pd.read_sql_query("SELECT * FROM CITY WHERE CountryCode LIKE 'USA'", conn)

C:\Users\Asus\AppData\Local\Temp\ipykernel_8308\3041809708.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM CITY WHERE CountryCode LIKE 'USA'", conn)

       ID          Name CountryCode        District  Population
0    3793      New York         USA        New York     8008278
1    3794   Los Angeles         USA      California     3694820
2    3795       Chicago         USA        Illinois     2896016
3    3796       Houston         USA           Texas     1953631
4    3797  Philadelphia         USA    Pennsylvania     1517550
..    ...           ...         ...             ...         ...
269  4062       Kenosha         USA       Wisconsin       89447
270  4063         Elgin         USA        Illinois       89408
271  4064        Odessa         USA           Texas       89293
272  4065        Carson         USA      California       89089
273  4066    Charleston         USA  South Carolina       89063

[274 rows x 5 columns]