In [1]:
import pandas as pd

In [3]:
df=pd.read_csv('track_data_final.csv')

# 1.How big is the Data ?

In [6]:
df.shape

(8778, 15)

# 2.How does the data Look like?

In [7]:
df.head()

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type
0,6pymOcrCnMuCWdgGVTvUgP,3,57,61,213173,False,Britney Spears,80.0,17755451.0,['pop'],325wcm5wMnlfjmKZ8PXIIn,The Singles Collection,2009-11-09,58,compilation
1,2lWc1iJlz2NVcStV5fbtPG,Clouds,1,67,158760,False,BUNT.,69.0,293734.0,['stutter house'],2ArRQNLxf9t0O0gvmG5Vsj,Clouds,2023-01-13,1,single
2,1msEuwSBneBKpVCZQcFTsU,Forever & Always (Taylor’s Version),11,63,225328,False,Taylor Swift,100.0,145396321.0,[],4hDok0OAJd57SGIT8xuWJH,Fearless (Taylor's Version),2021-04-09,26,album
3,7bcy34fBT2ap1L4bfPsl9q,I Didn't Change My Number,2,72,158463,True,Billie Eilish,90.0,118692183.0,[],0JGOiO34nwfUdDrD612dOp,Happier Than Ever,2021-07-30,16,album
4,0GLfodYacy3BJE7AI3A8en,Man Down,7,57,267013,False,Rihanna,90.0,68997177.0,[],5QG3tjE5L9F6O2vCAPph38,Loud,2010-01-01,13,album

In [8]:
df.sample(5) # 5 random rows

,track_id,track_name,track_number,track_popularity,track_duration_ms,explicit,artist_name,artist_popularity,artist_followers,artist_genres,album_id,album_name,album_release_date,album_total_tracks,album_type
3238,1ipnbmNWOpIRIVDWiZzNpV,Tangled - Kingdom Dance (Tavern Edition),1,0,138700,False,Colm R. McGuinness,56.0,169882.0,"['sea shanties', 'celtic']",2RyyO2q3J5nPrkoBWWA64m,Tangled - Kingdom Dance (Tavern Edition),2022-02-17,1,single
2338,5yuXdw2gb5bV4MXngcfvN6,Why Do We Fall?,11,1,122920,False,Hans Zimmer,77.0,4777574.0,['soundtrack'],3sGDniFo4e5r0bwmSL2upZ,The Dark Knight Rises,2012-08-29,15,album
476,5JqZ3oqF00jkT81foAFvqg,Prisoner (feat. Dua Lipa),1,1,169333,False,Miley Cyrus,81.0,26558356.0,[],3hUh17FzYZwwZyNjU9B3vL,Prisoner (feat. Dua Lipa),2020-11-20,1,single
6351,6buHoQU9OTdbJrAuniVwGL,Davy Jones,3,58,195240,False,Hans Zimmer,77.0,4780589.0,['soundtrack'],5eQEdvd6pq0uo2pQa56aUH,Pirates of the Caribbean: Dead Man's Chest (Or...,2006-01-01,12,compilation
4541,3cwDSDzTiWr5H5xMQhQ6Mx,Du hast,5,2,234226,False,Rammstein,77.0,11810806.0,"['industrial metal', 'metal', 'industrial rock...",6f4dhaPfZqf2JXewAvE4gq,Sehnsucht,1997-08-25,11,album

# 3.What is the data type of cols?

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8778 entries, 0 to 8777
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   track_id            8778 non-null   object
 1   track_name          8776 non-null   object
 2   track_number        8778 non-null   int64
 3   track_popularity    8778 non-null   int64
 4   track_duration_ms   8778 non-null   int64
 5   explicit            8778 non-null   bool
 6   artist_name         8774 non-null   object
 7   artist_popularity   8774 non-null   float64
 8   artist_followers    8774 non-null   float64
 9   artist_genres       8774 non-null   object
 10  album_id            8778 non-null   object
 11  album_name          8776 non-null   object
 12  album_release_date  8778 non-null   object
 13  album_total_tracks  8778 non-null   int64
 14  album_type          8778 non-null   object
dtypes: bool(1), float64(2), int64(4), object(8)
memory usage: 968.8+ KB

# 4.Are there any missing values?

In [10]:
df.isnull().sum()

track_id              0
track_name            2
track_number          0
track_popularity      0
track_duration_ms     0
explicit              0
artist_name           4
artist_popularity     4
artist_followers      4
artist_genres         4
album_id              0
album_name            2
album_release_date    0
album_total_tracks    0
album_type            0
dtype: int64

# 5.How does the data look mathematically?

In [11]:
df.describe()

,track_number,track_popularity,track_duration_ms,artist_popularity,artist_followers,album_total_tracks
count,8778.000000,8778.000000,8778.000000,8774.000000,8.774000e+03,8778.000000
mean,5.749487,52.232855,210157.791866,69.954981,2.435487e+07,13.779790
std,6.017938,24.075221,63326.841454,19.532783,3.813769e+07,11.797943
min,1.000000,0.000000,0.000000,0.000000,0.000000e+00,1.000000
25%,1.000000,39.000000,173921.250000,60.000000,5.152768e+05,6.000000
50%,4.000000,58.000000,207276.000000,74.000000,6.272266e+06,13.000000
75%,9.000000,71.000000,239693.250000,84.000000,3.055055e+07,17.000000
max,102.000000,100.000000,811077.000000,100.000000,1.455421e+08,181.000000

# 6. Are there duplicate values?

In [13]:
df.duplicated().sum()

np.int64(0)

# 7.How is the correlation between cols?

In [15]:
df.corr(numeric_only=True)

,track_number,track_popularity,track_duration_ms,explicit,artist_popularity,artist_followers,album_total_tracks
track_number,1.000000,-0.024465,0.070455,-0.009311,0.188944,0.221637,0.518550
track_popularity,-0.024465,1.000000,0.107116,0.126507,0.455739,0.226570,-0.047275
track_duration_ms,0.070455,0.107116,1.000000,0.009494,0.212325,0.175630,0.067941
explicit,-0.009311,0.126507,0.009494,1.000000,0.172190,0.102331,-0.058256
artist_popularity,0.188944,0.455739,0.212325,0.172190,1.000000,0.637667,0.200468
artist_followers,0.221637,0.226570,0.175630,0.102331,0.637667,1.000000,0.186392
album_total_tracks,0.518550,-0.047275,0.067941,-0.058256,0.200468,0.186392,1.000000